### ISSUE TITLE
How to build a multi-language API?

### ISSUE THREAD

**Issue by brunnolou** [lord-executor/kirby-json-api#3]
Is multi-language supported yet?
There is any example with multi-language support?

Thanks.

**Comment by brunnolou** [comment]
Thanks to @woudsma
In the file `JsonApiController.php` 
I replaced all:
```php
$page = page($id);
``` 
with:
```php
$page = site()->visit($id, kirby()->request()->query()->lang());
```

All the requests with `?lang=en`: `…/api/page/projects/project-a?lang=en`

**Comment by lord-executor** [comment]
Yeah.... Kirby's language handling is a bit odd at times.

1. There is an embarrassing bug in the language handling code of v-1.0.0 related to this which I'm about to fix. This (probably) won't change anything for you
2. The (current) default for language detection is the 'session' language, but that only works if the `$site->switchLanguage($language)` method is called at some point to initialize the user's session language. Unfortunately this happens nowhere in Kirby and the solution that I have used is ... a bit hacky. So, it _does_ work, but it is not well supported at this point.
3. It makes much more sense to explicitly add the language to the request with a `lang` parameter like you're doing. For the next release I will add this to the language handling options and make it the **default** and recommended scenario - with some documentation in the readme.

I'll let you know when the changes are ready.

**Comment by lord-executor** [comment]
As promised. New and improved language handling capabilities and the default is now set to look for the `lang` query string parameter. See the readme for more details.
